### PR TITLE
files: Files Storage. Download ZIP of all data.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Public data is written to files in Django file storage.

Thanks to the hooks in `indigo/jsondataferret.py` this is updated every time data changes (including removing a file if a public project goes private).

But also the commands

    updatefundfiles
    updateorganisationfiles
    updateprojectfiles

Can be used manually, if all files need to be updated (eg if a spreadsheet has changed)

Then the command `updatearchivefiles` is run regularly by cron.

It makes a Zip file of all existing files and puts it in the file storage area.

**Review by Lathrisk — APPROVED** [review]
:mage_man:

**Comment by Lathrisk** [comment]
Would it be useful to have an update all function, or is there not really a use case for that? I guess small change from extra manual step.

**Comment by ghost** [comment]
> Would it be useful to have an update all function, or is there not really a use case for that? 

I think there is a such a small use case for that - the mostly likely times you'll want to run an update command manually is when a spreadsheet changes, and they will probably change for 1 type only at a time

**Comment by ghost** [comment]
> Would it be useful to have an update all function

But also, very easy to add later if I'm wrong

**Pull request merged**
