### PR TITLE
data-model: Changes to Project and Organisation; Fields changed

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Note: Must run `python manage.py updatedata` after putting this live

**Comment by ghost** [comment]
### Organisation

Download the org spreadsheet template at: https://github.com/INDIGO-Initiative/database-app/raw/more-fields/indigo/spreadsheetform_guides/organisation_v004.xlsx

JSON Schema: https://github.com/INDIGO-Initiative/database-app/blob/more-fields/indigo/jsonschema/organisation.json

Example:

orgexample1

orgexabple2

I should make language codes uppercase, to match the uppercase country codes we already use?

### Project

Template: https://github.com/INDIGO-Initiative/database-app/raw/more-fields/indigo/spreadsheetform_guides/project_v011.xlsx

JSON Schema: https://github.com/INDIGO-Initiative/database-app/blob/more-fields/indigo/jsonschema/project.json

Example:

projexample

I've gone for a group so the source and notes are attached, and in a format where it's easy for us to add other fields in this group later if we want.

**Review by ScatteredInk — CHANGES_REQUESTED** [review]
It looks like enums that contain a comma within an option are breaking these out into separate choices for validation, so "Registered company, partnership or commercial association" becomes "Registered company", "partnership or commercial association" etc.

**Comment by ghost** [comment]
Good catch, thank you. The question was asked can we show it as commas in public data but as something else in admin spreadsheets - I will check that separately before returning to this pull request, as it turns out we already have one instance of this in the Technical Assistance Details tab of the Project spreadsheet.

**Comment by ghost** [comment]
> The question was asked can we show it as commas in public data but as something else in admin spreadsheets 

Now done

**Review by Lathrisk — APPROVED** [review]

**Pull request merged**
